name: "Api tests runner"

on:
  push:
    branches:
      - beta

jobs:
  tests_runner:
    runs-on: ubuntu-latest
    environment:
      name: beta
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: yarn --frozen-lockfile --silent

      - name: run tests
        run: yarn test
