name: "Api tests runner"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests_runner:
    runs-on: ubuntu-latest
    environment:
      url: "https://thawing-sierra-56257.herokuapp.com/"
      name: beta
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install dependencies
        run: yarn --frozen-lockfile --silent

      - name: run tests
        run: yarn test
